AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-execution-role
      Runtime: nodejs14.x
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log("Test Lambda executed");
            return "Success";
          };