AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: TestSecret
      SecretString: '{"username":"admin","password":"secret"}'